 CREATE TABLE links (
     id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
     trip_id UUID REFERENCES trips(id) ON DELETE CASCADE,

     title VARCHAR(255) NOT NULL,
     url VARCHAR(255) NOT NULL,

     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
 );
